### ISSUE TITLE
Get-PASSafeMember on quota owner

### ISSUE THREAD

**Issue by olegasdo** [pspete/psPAS#258]
**Describe the issue**
When trying to get permissions of the safe users with Get-PASSafeMember it returns an errors when trying to get quota owner permissions.
[403] Failed to update User or Group XXX. Reason: ITATS028E You are unauthorized to update requested privilege(s) for User XXX on Safe YYY.

**To Reproduce**
1.  execute Get-PASSafeMember -SafeName $memeber.SafeName -MemberName $memeber.UserName
Where $memeber.UserName is quota owner

**Expected behavior**
Shuld return permissions of the user

**Your Environment**
Include relevant details about your environment

* PowerShell Version: 5.1
* psPAS Version: 3.4.100
* CyberArk Version: PVWA 11.2

**Comment by pspete** [comment]
I do not think there is anything which can be fixed in the module code for this.
- If querying a safe for all its members, a `GET` request is used.
- If querying an individual safe members permissions on a safe, an empty `PUT` request is used; essentially an update which does not update anything.
In the GUI an exception would be returned if the quota owner is attempted to be updated, the same applies to the API.

**Comment by pspete** [comment]
@olegasdo - the next release of the module will provide additional details for the `MemberName` parameter and expected failure conditions:

```powershell
.PARAMETER MemberName
Specify the name of a safe member to return their safe permissions in full.
An empty PUT request (update) is sent to retrieve full safe permissions for a user, as such:
- You cannot report on the permissions of the user authenticated to the API.
- Reporting on the permissions of the Quota Owner is expected to fail.
```
