### ISSUE TITLE
Get-PASPlatformPSMConfig with PlatformID as String

### ISSUE THREAD

**Issue by redboyhun** [pspete/psPAS#390]
I can't find the ID of type Integer for a platform, but this command would require that one. Get-PASPlatform does not return the int ID

It would be nice if just like for other commands we could use the String type PlatformID

**Comment by pspete** [comment]
Consider completing the issue template so that the relevant version and command details can be discerned - this helps others help you.

See the related API documentation that Get-PASPlatform is based upon: 
https://pspas.pspete.dev/commands/Get-PASPlatform#related-links
There are definitely parameter combinations which would return an integer value relating to a platform (dependent on your version).

**Comment by pspete** [comment]
Integer `ID` is found under the `Details` property using the default ParameterSet
```powershell
Get-PASPlatform | Select-Object -ExpandProperty Details
```
