### ISSUE TITLE
Request to add Add-ObjectDetail as a public function

### ISSUE THREAD

**Issue by Ethlas** [pspete/psPAS#452]
**Is your feature request related to a problem? Please describe.**
We want to allow a module in https://github.com/cyberark/epv-api-scripts to work with psPAS. The module is Identity authentication. 

**Describe the solution you'd like**
It will be great if we can request psPAS module to be imported before importing the module (https://github.com/cyberark/epv-api-scripts/tree/main/Identity%20Authentication) to be used for psPAS.

**Describe alternatives you've considered**
We thought about just creating our own function. But if it is maintained already in this module and we are using it just to interact with this module it will be simpler to pull it.

**Additional context**

**Comment by pspete** [comment]
Hi @Ethlas - Add-ObjectDetail is borrowed from [RamblingCookieMonster](https://github.com/RamblingCookieMonster)'s repo here: https://github.com/RamblingCookieMonster/PowerShell/blob/master/Add-ObjectDetail.ps1

They also wrote a companion blog post on its usage: http://ramblingcookiemonster.github.io/Decorating-Objects/

Is my assumption correct that you are wanting to set a custom type name so that the output of the Identity Authentication module can be consumed by the `Use-PASSession` command in psPAS? If so, may be simpler to achieve with `Add-Member`

```powershell
Add-Member -InputObject $obj -TypeName Some.New.Type.Name
```

**Comment by pspete** [comment]
Closing for now... as normal module user interaction does not require the command to be invoked, it is unlikely to be made public as a module command.
