### ISSUE TITLE
Disabling HTTPS revocation check (no internet access)

### ISSUE THREAD

**Issue by oliverolli** [pspete/psPAS#73]
## Your Environment

* PowerShell Version: PSVersion     5.1.14409.1012
* psPAS Branch & Version: 1.3.0
* CyberArk Version: 10.3

## Expected Behaviour
We would like to be able to connect to cyberark via on a client machine without internet connection. (through a parameter is fine)

## Current Behaviour

Calling the new-PASSession results in the following error: Microsoft.PowerShell.Commands.WriteErrorException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

as far as we can tell this is caused by powershell failing to perform revocation check of the PVWA servers' https certificate. 

## Possible Solution
It would be preferred if a parameter for skipping the revocation check. Ideally without skipping the entire certificate check.

## Steps to Reproduce (for bug reports)

1 . call new-PASSession from a server without internet connection (but has LAN access to cyberark via HTTPS)

2 .

3 .

4 .

## Sample Output
13:34:53 VERBOSE: Performing the operation "Logon with User '****'" on target 
13:34:53 "https://pam.nchosting.dk//PasswordVault".
13:34:53 VERBOSE: Setting Security Protocol to TLS12
13:34:54 VERBOSE: POST https://pam.nchosting.dk//PasswordVault/WebServices/auth/Cyberark/CyberArkAuthenticationService.svc/Logon
13:34:54  with -1-byte payload
13:34:56 Microsoft.PowerShell.Commands.WriteErrorException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

## Context
I am trying to connect to cyberark via a script being run on a Jenkins server without internet connection

**Comment by pspete** [comment]
Hi @oliverolli - your steps to reproduce didn't result in the behavior you experience (for me at least).
What happens when you browse to the PVWA from your Jenkins server? Do you get a secure connection? Cert error?
Also, is the additional slash in your Url (before PasswordVault) there during execution?

**Comment by oliverolli** [comment]
Hi @pspete - We are trying to get a more detailed error message. Browsing to PVWA from the Jenkins server gave a certificate error.

**Comment by pspete** [comment]
Thanks for checking that @oliverolli - I am assuming PVWA does not show the SSL error from other locations from which you can access it?
Does the Jenkins server trust all the necessary certificates in the chain to be able to validate the PVWA certificate (root, intermediate etc)? 
HTTPS between your server & PVWA should be possible, I am not convinced this is due to a failed CRL check currently - will wait for your update.

**Comment by oliverolli** [comment]
Hi again.
We found the error and fixed it. Sorry about the inconvenience.
